#%RAML 1.0 NamedExample
value: |
  {
    "address": {
        "address_line_1": "Main street 242",
        "city": "San Francisco",
        "state": "California",
        "zip_code": "90222",
        "country": "USA"
    },
    "gender": "female",
    "name": "Jane Doe",
    "email": "janedoe@example.com",
    "username": "jd",
    "phone": "555-12345",
    "ssn": "123-45-6789",
    "id": "537cceb2-0abb-46de-ba53-e9123673ce01"
  }