#%RAML 1.0 NamedExample
value: |
  {
    "username": "login",
    "password": "password",
    "name": "Peter Pan",
    "phone": "608-990-9754",
    "ssn": "123456789",
    "email": "peter.pan@email.com",
    "gender": "male",
    "address":
      {
        "country": "United States of America",
        "city": "San Francisco",
        "zip_code": "53703",
        "state": "California",
        "address_line_1": "1855 Folsom Street"
      }
  }